const forecastWeatherData = {
    "location": {
        "name": "Boston",
        "region": "Massachusetts",
        "country": "United States of America",
        "lat": 42.36,
        "lon": -71.06,
        "tz_id": "America/New_York",
        "localtime_epoch": 1629810964,
        "localtime": "2021-08-24 9:16"
    },
    "current": {
        "last_updated_epoch": 1629810900,
        "last_updated": "2021-08-24 09:15",
        "temp_c": 22.8,
        "temp_f": 73.0,
        "is_day": 1,
        "condition": {
            "text": "Overcast",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
            "code": 1009
        },
        "wind_mph": 9.4,
        "wind_kph": 15.1,
        "wind_degree": 330,
        "wind_dir": "NNW",
        "pressure_mb": 1011.0,
        "pressure_in": 29.85,
        "precip_mm": 0.2,
        "precip_in": 0.01,
        "humidity": 87,
        "cloud": 100,
        "feelslike_c": 25.3,
        "feelslike_f": 77.6,
        "vis_km": 4.8,
        "vis_miles": 2.0,
        "uv": 1.0,
        "gust_mph": 13.0,
        "gust_kph": 20.9
    },
    "forecast": {
        "forecastday": [
            {
                "date": "2021-08-24",
                "date_epoch": 1629763200,
                "day": {
                    "maxtemp_c": 29.9,
                    "maxtemp_f": 85.8,
                    "mintemp_c": 19.8,
                    "mintemp_f": 67.6,
                    "avgtemp_c": 23.8,
                    "avgtemp_f": 74.9,
                    "maxwind_mph": 8.5,
                    "maxwind_kph": 13.7,
                    "totalprecip_mm": 2.3,
                    "totalprecip_in": 0.09,
                    "avgvis_km": 8.3,
                    "avgvis_miles": 5.0,
                    "avghumidity": 81.0,
                    "daily_will_it_rain": 1,
                    "daily_chance_of_rain": 92,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Patchy rain possible",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                        "code": 1063
                    },
                    "uv": 7.0
                },
                "astro": {
                    "sunrise": "06:01 AM",
                    "sunset": "07:31 PM",
                    "moonrise": "09:00 PM",
                    "moonset": "08:04 AM",
                    "moon_phase": "Waning Gibbous",
                    "moon_illumination": "83"
                },
                "hour": [
                    {
                        "time_epoch": 1629777600,
                        "time": "2021-08-24 00:00",
                        "temp_c": 20.4,
                        "temp_f": 68.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Fog",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/248.png",
                            "code": 1135
                        },
                        "wind_mph": 5.1,
                        "wind_kph": 8.3,
                        "wind_degree": 47,
                        "wind_dir": "NE",
                        "pressure_mb": 1010.0,
                        "pressure_in": 29.81,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 98,
                        "cloud": 100,
                        "feelslike_c": 20.4,
                        "feelslike_f": 68.7,
                        "windchill_c": 20.4,
                        "windchill_f": 68.7,
                        "heatindex_c": 20.4,
                        "heatindex_f": 68.7,
                        "dewpoint_c": 20.0,
                        "dewpoint_f": 68.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 0.0,
                        "vis_miles": 0.0,
                        "gust_mph": 9.4,
                        "gust_kph": 15.1,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1629781200,
                        "time": "2021-08-24 01:00",
                        "temp_c": 20.3,
                        "temp_f": 68.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Light rain shower",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                            "code": 1240
                        },
                        "wind_mph": 5.1,
                        "wind_kph": 8.3,
                        "wind_degree": 51,
                        "wind_dir": "NE",
                        "pressure_mb": 1009.0,
                        "pressure_in": 29.8,
                        "precip_mm": 0.4,
                        "precip_in": 0.02,
                        "humidity": 98,
                        "cloud": 100,
                        "feelslike_c": 20.3,
                        "feelslike_f": 68.5,
                        "windchill_c": 20.3,
                        "windchill_f": 68.5,
                        "heatindex_c": 20.3,
                        "heatindex_f": 68.5,
                        "dewpoint_c": 20.0,
                        "dewpoint_f": 68.0,
                        "will_it_rain": 1,
                        "chance_of_rain": 92,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.6,
                        "gust_kph": 15.5,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1629784800,
                        "time": "2021-08-24 02:00",
                        "temp_c": 20.4,
                        "temp_f": 68.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Fog",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/248.png",
                            "code": 1135
                        },
                        "wind_mph": 4.9,
                        "wind_kph": 7.9,
                        "wind_degree": 44,
                        "wind_dir": "NE",
                        "pressure_mb": 1009.0,
                        "pressure_in": 29.79,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 99,
                        "cloud": 100,
                        "feelslike_c": 20.4,
                        "feelslike_f": 68.7,
                        "windchill_c": 20.4,
                        "windchill_f": 68.7,
                        "heatindex_c": 20.4,
                        "heatindex_f": 68.7,
                        "dewpoint_c": 20.2,
                        "dewpoint_f": 68.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 0.0,
                        "vis_miles": 0.0,
                        "gust_mph": 8.7,
                        "gust_kph": 14.0,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1629788400,
                        "time": "2021-08-24 03:00",
                        "temp_c": 20.3,
                        "temp_f": 68.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Light rain shower",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                            "code": 1240
                        },
                        "wind_mph": 5.8,
                        "wind_kph": 9.4,
                        "wind_degree": 29,
                        "wind_dir": "NNE",
                        "pressure_mb": 1009.0,
                        "pressure_in": 29.78,
                        "precip_mm": 0.6,
                        "precip_in": 0.02,
                        "humidity": 99,
                        "cloud": 100,
                        "feelslike_c": 20.3,
                        "feelslike_f": 68.5,
                        "windchill_c": 20.3,
                        "windchill_f": 68.5,
                        "heatindex_c": 20.3,
                        "heatindex_f": 68.5,
                        "dewpoint_c": 20.1,
                        "dewpoint_f": 68.2,
                        "will_it_rain": 1,
                        "chance_of_rain": 89,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.8,
                        "gust_kph": 15.8,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1629792000,
                        "time": "2021-08-24 04:00",
                        "temp_c": 20.3,
                        "temp_f": 68.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Light rain shower",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                            "code": 1240
                        },
                        "wind_mph": 6.3,
                        "wind_kph": 10.1,
                        "wind_degree": 15,
                        "wind_dir": "NNE",
                        "pressure_mb": 1009.0,
                        "pressure_in": 29.78,
                        "precip_mm": 0.3,
                        "precip_in": 0.01,
                        "humidity": 99,
                        "cloud": 100,
                        "feelslike_c": 20.3,
                        "feelslike_f": 68.5,
                        "windchill_c": 20.3,
                        "windchill_f": 68.5,
                        "heatindex_c": 20.3,
                        "heatindex_f": 68.5,
                        "dewpoint_c": 20.1,
                        "dewpoint_f": 68.2,
                        "will_it_rain": 1,
                        "chance_of_rain": 75,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 10.3,
                        "gust_kph": 16.6,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1629795600,
                        "time": "2021-08-24 05:00",
                        "temp_c": 20.2,
                        "temp_f": 68.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Light rain shower",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                            "code": 1240
                        },
                        "wind_mph": 7.6,
                        "wind_kph": 12.2,
                        "wind_degree": 359,
                        "wind_dir": "N",
                        "pressure_mb": 1009.0,
                        "pressure_in": 29.8,
                        "precip_mm": 0.7,
                        "precip_in": 0.03,
                        "humidity": 99,
                        "cloud": 100,
                        "feelslike_c": 20.2,
                        "feelslike_f": 68.4,
                        "windchill_c": 20.2,
                        "windchill_f": 68.4,
                        "heatindex_c": 20.2,
                        "heatindex_f": 68.4,
                        "dewpoint_c": 20.0,
                        "dewpoint_f": 68.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 68,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.9,
                        "gust_kph": 19.1,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1629799200,
                        "time": "2021-08-24 06:00",
                        "temp_c": 19.9,
                        "temp_f": 67.8,
                        "is_day": 0,
                        "condition": {
                            "text": "Light rain shower",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                            "code": 1240
                        },
                        "wind_mph": 8.5,
                        "wind_kph": 13.7,
                        "wind_degree": 353,
                        "wind_dir": "N",
                        "pressure_mb": 1010.0,
                        "pressure_in": 29.81,
                        "precip_mm": 0.2,
                        "precip_in": 0.01,
                        "humidity": 99,
                        "cloud": 100,
                        "feelslike_c": 19.9,
                        "feelslike_f": 67.8,
                        "windchill_c": 19.9,
                        "windchill_f": 67.8,
                        "heatindex_c": 19.9,
                        "heatindex_f": 67.8,
                        "dewpoint_c": 19.7,
                        "dewpoint_f": 67.5,
                        "will_it_rain": 1,
                        "chance_of_rain": 75,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 13.0,
                        "gust_kph": 20.9,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1629802800,
                        "time": "2021-08-24 07:00",
                        "temp_c": 19.8,
                        "temp_f": 67.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Fog",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/248.png",
                            "code": 1135
                        },
                        "wind_mph": 7.4,
                        "wind_kph": 11.9,
                        "wind_degree": 356,
                        "wind_dir": "N",
                        "pressure_mb": 1010.0,
                        "pressure_in": 29.83,
                        "precip_mm": 0.1,
                        "precip_in": 0.0,
                        "humidity": 99,
                        "cloud": 100,
                        "feelslike_c": 19.8,
                        "feelslike_f": 67.6,
                        "windchill_c": 19.8,
                        "windchill_f": 67.6,
                        "heatindex_c": 19.8,
                        "heatindex_f": 67.6,
                        "dewpoint_c": 19.6,
                        "dewpoint_f": 67.3,
                        "will_it_rain": 1,
                        "chance_of_rain": 89,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 0.0,
                        "vis_miles": 0.0,
                        "gust_mph": 11.2,
                        "gust_kph": 18.0,
                        "uv": 4.0
                    },
                    {
                        "time_epoch": 1629806400,
                        "time": "2021-08-24 08:00",
                        "temp_c": 20.2,
                        "temp_f": 68.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Fog",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/248.png",
                            "code": 1135
                        },
                        "wind_mph": 6.9,
                        "wind_kph": 11.2,
                        "wind_degree": 352,
                        "wind_dir": "N",
                        "pressure_mb": 1011.0,
                        "pressure_in": 29.85,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 98,
                        "cloud": 100,
                        "feelslike_c": 20.2,
                        "feelslike_f": 68.4,
                        "windchill_c": 20.2,
                        "windchill_f": 68.4,
                        "heatindex_c": 20.2,
                        "heatindex_f": 68.4,
                        "dewpoint_c": 19.9,
                        "dewpoint_f": 67.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 0.0,
                        "vis_miles": 0.0,
                        "gust_mph": 9.8,
                        "gust_kph": 15.8,
                        "uv": 5.0
                    },
                    {
                        "time_epoch": 1629810000,
                        "time": "2021-08-24 09:00",
                        "temp_c": 21.2,
                        "temp_f": 70.2,
                        "is_day": 1,
                        "condition": {
                            "text": "Cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                            "code": 1006
                        },
                        "wind_mph": 7.4,
                        "wind_kph": 11.9,
                        "wind_degree": 349,
                        "wind_dir": "N",
                        "pressure_mb": 1011.0,
                        "pressure_in": 29.86,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 94,
                        "cloud": 84,
                        "feelslike_c": 21.2,
                        "feelslike_f": 70.2,
                        "windchill_c": 21.2,
                        "windchill_f": 70.2,
                        "heatindex_c": 24.2,
                        "heatindex_f": 75.6,
                        "dewpoint_c": 20.2,
                        "dewpoint_f": 68.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.8,
                        "gust_kph": 15.8,
                        "uv": 5.0
                    },
                    {
                        "time_epoch": 1629813600,
                        "time": "2021-08-24 10:00",
                        "temp_c": 23.0,
                        "temp_f": 73.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                            "code": 1006
                        },
                        "wind_mph": 6.0,
                        "wind_kph": 9.7,
                        "wind_degree": 349,
                        "wind_dir": "N",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.88,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 85,
                        "cloud": 70,
                        "feelslike_c": 25.1,
                        "feelslike_f": 77.2,
                        "windchill_c": 23.0,
                        "windchill_f": 73.4,
                        "heatindex_c": 25.1,
                        "heatindex_f": 77.2,
                        "dewpoint_c": 20.3,
                        "dewpoint_f": 68.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 7.2,
                        "gust_kph": 11.5,
                        "uv": 5.0
                    },
                    {
                        "time_epoch": 1629817200,
                        "time": "2021-08-24 11:00",
                        "temp_c": 26.6,
                        "temp_f": 79.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 4.9,
                        "wind_kph": 7.9,
                        "wind_degree": 346,
                        "wind_dir": "NNW",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.88,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 70,
                        "cloud": 55,
                        "feelslike_c": 28.6,
                        "feelslike_f": 83.5,
                        "windchill_c": 26.6,
                        "windchill_f": 79.9,
                        "heatindex_c": 28.6,
                        "heatindex_f": 83.5,
                        "dewpoint_c": 20.7,
                        "dewpoint_f": 69.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 5.6,
                        "gust_kph": 9.0,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1629820800,
                        "time": "2021-08-24 12:00",
                        "temp_c": 28.6,
                        "temp_f": 83.5,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 3.8,
                        "wind_kph": 6.1,
                        "wind_degree": 350,
                        "wind_dir": "N",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.88,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 62,
                        "cloud": 39,
                        "feelslike_c": 30.9,
                        "feelslike_f": 87.6,
                        "windchill_c": 28.6,
                        "windchill_f": 83.5,
                        "heatindex_c": 30.9,
                        "heatindex_f": 87.6,
                        "dewpoint_c": 20.6,
                        "dewpoint_f": 69.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 4.5,
                        "gust_kph": 7.2,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1629824400,
                        "time": "2021-08-24 13:00",
                        "temp_c": 29.5,
                        "temp_f": 85.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                            "code": 1006
                        },
                        "wind_mph": 3.1,
                        "wind_kph": 5.0,
                        "wind_degree": 352,
                        "wind_dir": "N",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.88,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 57,
                        "cloud": 66,
                        "feelslike_c": 31.6,
                        "feelslike_f": 88.9,
                        "windchill_c": 29.5,
                        "windchill_f": 85.1,
                        "heatindex_c": 31.6,
                        "heatindex_f": 88.9,
                        "dewpoint_c": 19.9,
                        "dewpoint_f": 67.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 3.6,
                        "gust_kph": 5.8,
                        "uv": 6.0
                    },
                    {
                        "time_epoch": 1629828000,
                        "time": "2021-08-24 14:00",
                        "temp_c": 29.9,
                        "temp_f": 85.8,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 2.2,
                        "wind_kph": 3.6,
                        "wind_degree": 24,
                        "wind_dir": "NNE",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.87,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 54,
                        "cloud": 53,
                        "feelslike_c": 31.9,
                        "feelslike_f": 89.4,
                        "windchill_c": 29.9,
                        "windchill_f": 85.8,
                        "heatindex_c": 31.9,
                        "heatindex_f": 89.4,
                        "dewpoint_c": 19.6,
                        "dewpoint_f": 67.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 2.5,
                        "gust_kph": 4.0,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1629831600,
                        "time": "2021-08-24 15:00",
                        "temp_c": 29.1,
                        "temp_f": 84.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 2.5,
                        "wind_kph": 4.0,
                        "wind_degree": 76,
                        "wind_dir": "ENE",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.87,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 57,
                        "cloud": 37,
                        "feelslike_c": 31.1,
                        "feelslike_f": 88.0,
                        "windchill_c": 29.1,
                        "windchill_f": 84.4,
                        "heatindex_c": 31.1,
                        "heatindex_f": 88.0,
                        "dewpoint_c": 19.7,
                        "dewpoint_f": 67.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 2.9,
                        "gust_kph": 4.7,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1629835200,
                        "time": "2021-08-24 16:00",
                        "temp_c": 26.9,
                        "temp_f": 80.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                            "code": 1006
                        },
                        "wind_mph": 2.7,
                        "wind_kph": 4.3,
                        "wind_degree": 106,
                        "wind_dir": "ESE",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.88,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 66,
                        "cloud": 87,
                        "feelslike_c": 28.7,
                        "feelslike_f": 83.7,
                        "windchill_c": 26.9,
                        "windchill_f": 80.4,
                        "heatindex_c": 28.7,
                        "heatindex_f": 83.7,
                        "dewpoint_c": 19.9,
                        "dewpoint_f": 67.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 4.3,
                        "gust_kph": 6.8,
                        "uv": 6.0
                    },
                    {
                        "time_epoch": 1629838800,
                        "time": "2021-08-24 17:00",
                        "temp_c": 25.6,
                        "temp_f": 78.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                            "code": 1006
                        },
                        "wind_mph": 2.9,
                        "wind_kph": 4.7,
                        "wind_degree": 134,
                        "wind_dir": "SE",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.89,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 71,
                        "cloud": 71,
                        "feelslike_c": 27.4,
                        "feelslike_f": 81.3,
                        "windchill_c": 25.6,
                        "windchill_f": 78.1,
                        "heatindex_c": 27.4,
                        "heatindex_f": 81.3,
                        "dewpoint_c": 20.0,
                        "dewpoint_f": 68.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 5.4,
                        "gust_kph": 8.6,
                        "uv": 6.0
                    },
                    {
                        "time_epoch": 1629842400,
                        "time": "2021-08-24 18:00",
                        "temp_c": 25.8,
                        "temp_f": 78.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 3.4,
                        "wind_kph": 5.4,
                        "wind_degree": 168,
                        "wind_dir": "SSE",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.91,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 71,
                        "cloud": 54,
                        "feelslike_c": 27.6,
                        "feelslike_f": 81.7,
                        "windchill_c": 25.8,
                        "windchill_f": 78.4,
                        "heatindex_c": 27.6,
                        "heatindex_f": 81.7,
                        "dewpoint_c": 20.2,
                        "dewpoint_f": 68.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 6.3,
                        "gust_kph": 10.1,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1629846000,
                        "time": "2021-08-24 19:00",
                        "temp_c": 25.6,
                        "temp_f": 78.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 3.6,
                        "wind_kph": 5.8,
                        "wind_degree": 190,
                        "wind_dir": "S",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.92,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 73,
                        "cloud": 35,
                        "feelslike_c": 27.5,
                        "feelslike_f": 81.5,
                        "windchill_c": 25.6,
                        "windchill_f": 78.1,
                        "heatindex_c": 27.5,
                        "heatindex_f": 81.5,
                        "dewpoint_c": 20.4,
                        "dewpoint_f": 68.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 6.9,
                        "gust_kph": 11.2,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1629849600,
                        "time": "2021-08-24 20:00",
                        "temp_c": 25.1,
                        "temp_f": 77.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 3.8,
                        "wind_kph": 6.1,
                        "wind_degree": 212,
                        "wind_dir": "SSW",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.94,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 75,
                        "cloud": 32,
                        "feelslike_c": 27.0,
                        "feelslike_f": 80.6,
                        "windchill_c": 25.1,
                        "windchill_f": 77.2,
                        "heatindex_c": 27.0,
                        "heatindex_f": 80.6,
                        "dewpoint_c": 20.4,
                        "dewpoint_f": 68.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 8.1,
                        "gust_kph": 13.0,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1629853200,
                        "time": "2021-08-24 21:00",
                        "temp_c": 25.3,
                        "temp_f": 77.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 4.3,
                        "wind_kph": 6.8,
                        "wind_degree": 232,
                        "wind_dir": "SW",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.96,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 74,
                        "cloud": 18,
                        "feelslike_c": 27.2,
                        "feelslike_f": 81.0,
                        "windchill_c": 25.3,
                        "windchill_f": 77.5,
                        "heatindex_c": 27.2,
                        "heatindex_f": 81.0,
                        "dewpoint_c": 20.4,
                        "dewpoint_f": 68.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 8.9,
                        "gust_kph": 14.4,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1629856800,
                        "time": "2021-08-24 22:00",
                        "temp_c": 24.2,
                        "temp_f": 75.6,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 4.7,
                        "wind_kph": 7.6,
                        "wind_degree": 251,
                        "wind_dir": "WSW",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.97,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 78,
                        "cloud": 13,
                        "feelslike_c": 26.1,
                        "feelslike_f": 79.0,
                        "windchill_c": 24.2,
                        "windchill_f": 75.6,
                        "heatindex_c": 26.1,
                        "heatindex_f": 79.0,
                        "dewpoint_c": 20.1,
                        "dewpoint_f": 68.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.8,
                        "gust_kph": 15.8,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1629860400,
                        "time": "2021-08-24 23:00",
                        "temp_c": 23.8,
                        "temp_f": 74.8,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 5.1,
                        "wind_kph": 8.3,
                        "wind_degree": 271,
                        "wind_dir": "W",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.98,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 79,
                        "cloud": 22,
                        "feelslike_c": 25.7,
                        "feelslike_f": 78.3,
                        "windchill_c": 23.8,
                        "windchill_f": 74.8,
                        "heatindex_c": 25.7,
                        "heatindex_f": 78.3,
                        "dewpoint_c": 19.9,
                        "dewpoint_f": 67.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 10.7,
                        "gust_kph": 17.3,
                        "uv": 1.0
                    }
                ]
            }
        ]
    },
    "alerts": {
        "alert": [
            
        ]
    }
}

export default forecastWeatherData;